services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: tron-backend:local
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tron-frontend:local
    ports:
      - "8081:80"
    restart: unless-stopped
